# Generated by Django 2.2.26 on 2022-05-10 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_postcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='ref_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postcomment_ref_comment', to='home.PostComment'),
        ),
    ]
