# Generated by Django 2.2.26 on 2022-05-10 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0009_upvotepost'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownvotePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('downvote_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downvotepost_downvote_by', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downvotepost_post', to='home.Post')),
            ],
        ),
    ]
