# Generated by Django 2.2.26 on 2022-05-10 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_downvotepost"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="postcomment",
            name="post",
        ),
    ]
